config/routes.rb
Rails.application.routes.draw do

  #added a route called filter, to filter the orders based on different
  # parameters, so whatever parameter we pass, we can filter them
  post :filter, to: 'orders#filter'
  #making orders pages the home page
  root 'orders#index'

  resources :positions
  resources :orders
  resources :menu_items
  resources :users




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :users
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:position)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :position_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.position %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @position.position %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>