config/routes.rb
Rails.application.routes.draw do

  #added a route called filter, to filter the orders based on different
  # parameters, so whatever parameter we pass, we can filter them
  post :filter, to: 'orders#filter'
  #making orders pages the home page
  root 'orders#index'

  resources :positions
  resources :orders
  resources :menu_items
  resources :users




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:item_name, :price, :id)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, id: :menu_item_item_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :menu_item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Price</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.item_name %></td>
        <td><%= menu_item.price %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @menu_item.item_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>