config/routes.rb
Rails.application.routes.draw do

  #added a route called filter, to filter the orders based on different
  # parameters, so whatever parameter we pass, we can filter them
  post :filter, to: 'orders#filter'
  #making orders pages the home page
  root 'orders#index'

  resources :positions
  resources :orders
  resources :menu_items
  resources :users




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu_item
  validates :menu_item, presence: true
  after_save :calculate_total
  accepts_nested_attributes_for :menu_item,
                                reject_if: :all_blank, allow_destroy: true

  #what is used to filter, scope is a method, find the dates in range
  # checks for both start and end
  scope :in_range, ->(start_date, end_date) { where("date_of_sale >= ? AND date_of_sale <= ?", start_date, end_date) }
  def calculate_total
    subtotal = menu_item.price
    tax = subtotal / 10
    total = tax + subtotal
    update_columns(subtotal: subtotal, tax: tax, total: total)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    #where the actual filtering happens, if the start date and
    # end date is requested, it finds the dates
    # and filters them, the filter is only done if we pass params to the filter action
    @orders =
        if params[:start_date] && params[:end_date]
          Order.in_range(params[:start_date]&.to_date, params[:end_date]&.to_date)
        else
          Order.all
        end
  end

  #made filter action where we passing filter parameters to the index action
  def filter
    redirect_to orders_path(filter_params)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order,).permit(:name, :subtotal, :total,:tax,:menu_item_id, :date_of_sale)
    end
#where you list the params for the action filter that we made
  def filter_params
    params.permit( :start_date, :end_date)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- id: :order_name -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name  %>
  </div>

  <div class="field">
    <%= form.label "Date of Sale:" %>
    <%= form.date_select :date_of_sale, id: :order_date_of_sale %>
  </div>

  <div class="field">
    <%= form.label "What are you ordering?" %>
    <%= form.collection_select :menu_item_id, MenuItem.all, :id, :item_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Orders</h1>


<script>
  alert("Make sure you meet your daily sales quota!");
</script>

<!-- form for the filter field, it finds the orders controller, and then
does the action filter, start date and end date are the params it finds. -->
<%= form_for :post, url: url_for(controller: 'orders', action: "filter") do |f| %>
 *MUST put start date and end date.
  <div class="field">
    <%= label_tag "Start Date" %>
    <%= date_field_tag :start_date %>
  </div>

  <div class="field">
    <%= label_tag "End Date" %>
    <%= date_field_tag :end_date %>
  </div>
  <%= f.submit 'Filter' %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of Sale</th>
      <th>Subtotal</th>
      <th>Total</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.date_of_sale %></td>
        <td><%= order.subtotal %></td>
        <td><%= order.total %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Date of Sale:</strong>
  <%= @order.date_of_sale %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @order.subtotal %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>